import os
import dotenv
import torch

dotenv.load_dotenv()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

VLLM_BASE_URL = os.getenv("VLLM_BASE_URL")
VLLM_API_KEY = os.getenv("VLLM_API_KEY")
VLLM_MODEL_NAME = os.getenv("VLLM_MODEL_NAME")
VLLM_TOKENIZER= os.getenv("VLLM_TOKENIZER")
MAX_TOTAL_TOKENS = int(os.getenv("MAX_TOTAL_TOKENS"))

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
VRAM_USAGE_FRACTION = 1.0
DEBUG = True

BATCH_SIZE_DETECTION = 3
BATCH_SIZE_OCR = 12
BATCH_SIZE_CROP_EMBEDDING = 20

LIMIT_TRY_AGAIN = 2

HISTORY_WINDOW_SIZE = 2
CHARACTER_DETECTION_THRESHOLD = 0.1
TEXT_CLASSIFICATION_THRESHOLD = 0.3
ETA_FOR_CHARACTER_NAMING = 0.85
TEXT_CHARACTER_MATCHING_THRESHOLD = 0.55
CHARACTER_CHARACTER_MATCHING_THRESHOLD = 0.45
TEXT_TAIL_MATCHING_THRESHOLD = 0.1
TAIL_DETECTION_THRESHOLD = 0.05
