"""Update schema: normalize mapping_name and translate_dict

Revision ID: 440ebebfb75f
Revises: 5c486cdb1ef3
Create Date: 2025-11-24 13:17:58.325646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '440ebebfb75f'
down_revision: Union[str, None] = '5c486cdb1ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Tạo enum types trước khi sử dụng (nếu chưa tồn tại)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE topic AS ENUM ('BASIC', 'HISTORY_FICTION', 'WUXIA', 'XIANXIA', 'COURT_INTRIGUE', 'FANTASY_GENERAL');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE language AS ENUM ('ENGLISH', 'VIETNAMESE', 'JAPANESE', 'KOREAN', 'CHINESE', 'FRENCH');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Sử dụng postgresql.ENUM với create_type=False để không tự động tạo lại
    language_enum_type = postgresql.ENUM('ENGLISH', 'VIETNAMESE', 'JAPANESE', 'KOREAN', 'CHINESE', 'FRENCH', name='language', create_type=False)
    
    op.create_table('translate_dict_stories',
    sa.Column('language', language_enum_type, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('dictionary', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translate_dict_stories_id'), 'translate_dict_stories', ['id'], unique=False)
    op.create_index(op.f('ix_translate_dict_stories_language'), 'translate_dict_stories', ['language'], unique=False)
    op.create_index(op.f('ix_translate_dict_stories_story_id'), 'translate_dict_stories', ['story_id'], unique=False)
    op.create_table('mapping_names',
    sa.Column('language', language_enum_type, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('new_name', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_names_character_id'), 'mapping_names', ['character_id'], unique=False)
    op.create_index(op.f('ix_mapping_names_id'), 'mapping_names', ['id'], unique=False)
    op.create_index(op.f('ix_mapping_names_language'), 'mapping_names', ['language'], unique=False)
    # Migrate data từ VARCHAR sang Enum trước khi ALTER COLUMN
    # Chuyển đổi story_type từ string sang enum value
    op.execute("""
        UPDATE stories 
        SET story_type = CASE 
            WHEN story_type = 'truyện hiện đại' THEN 'BASIC'
            WHEN story_type = 'truyện cổ trang' THEN 'HISTORY_FICTION'
            WHEN story_type = 'wuxia' THEN 'WUXIA'
            WHEN story_type = 'xianxia' THEN 'XIANXIA'
            WHEN story_type = 'court_intrigue' THEN 'COURT_INTRIGUE'
            WHEN story_type = 'fantasy_general' THEN 'FANTASY_GENERAL'
            ELSE 'BASIC'
        END
    """)
    
    # Chuyển đổi source_language từ string sang enum value
    op.execute("""
        UPDATE stories 
        SET source_language = UPPER(source_language)
    """)
    
    # Thêm cột source_name với giá trị mặc định từ name
    op.add_column('characters', sa.Column('source_name', sa.String(length=255), nullable=True))
    op.execute("UPDATE characters SET source_name = name WHERE source_name IS NULL")
    op.alter_column('characters', 'source_name', nullable=False)
    op.drop_column('characters', 'name')
    
    # ALTER COLUMN từ VARCHAR sang ENUM với cast
    topic_enum_type = postgresql.ENUM('BASIC', 'HISTORY_FICTION', 'WUXIA', 'XIANXIA', 'COURT_INTRIGUE', 'FANTASY_GENERAL', name='topic', create_type=False)
    
    op.execute("""
        ALTER TABLE stories 
        ALTER COLUMN story_type TYPE topic 
        USING story_type::topic
    """)
    
    op.execute("""
        ALTER TABLE stories 
        ALTER COLUMN source_language TYPE language 
        USING source_language::language
    """)
    
    op.drop_column('stories', 'mapping_name')
    op.drop_column('stories', 'translate_dict')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Chuyển đổi enum về string trước khi drop enum types
    op.execute("""
        ALTER TABLE stories 
        ALTER COLUMN story_type TYPE VARCHAR(50) 
        USING story_type::text
    """)
    
    op.execute("""
        ALTER TABLE stories 
        ALTER COLUMN source_language TYPE VARCHAR(50) 
        USING source_language::text
    """)
    
    op.add_column('stories', sa.Column('translate_dict', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('stories', sa.Column('mapping_name', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('characters', 'source_name')
    op.drop_index(op.f('ix_mapping_names_language'), table_name='mapping_names')
    op.drop_index(op.f('ix_mapping_names_id'), table_name='mapping_names')
    op.drop_index(op.f('ix_mapping_names_character_id'), table_name='mapping_names')
    op.drop_table('mapping_names')
    op.drop_index(op.f('ix_translate_dict_stories_story_id'), table_name='translate_dict_stories')
    op.drop_index(op.f('ix_translate_dict_stories_language'), table_name='translate_dict_stories')
    op.drop_index(op.f('ix_translate_dict_stories_id'), table_name='translate_dict_stories')
    op.drop_table('translate_dict_stories')
    
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS topic")
    op.execute("DROP TYPE IF EXISTS language")
    # ### end Alembic commands ###

