"""Initial migration

Revision ID: 5c486cdb1ef3
Revises: 
Create Date: 2025-11-23 23:25:56.644103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c486cdb1ef3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('story_name', sa.String(length=255), nullable=False),
    sa.Column('story_type', sa.String(length=50), nullable=False),
    sa.Column('source_language', sa.String(length=50), nullable=False),
    sa.Column('mapping_name', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('translate_dict', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.create_index(op.f('ix_stories_story_name'), 'stories', ['story_name'], unique=True)
    op.create_table('characters',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('face', sa.Text(), nullable=True),
    sa.Column('hair', sa.Text(), nullable=True),
    sa.Column('eyes', sa.Text(), nullable=True),
    sa.Column('outfit', sa.Text(), nullable=True),
    sa.Column('accessories', sa.Text(), nullable=True),
    sa.Column('distinctive_features', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_index(op.f('ix_characters_story_id'), 'characters', ['story_id'], unique=False)
    op.create_table('episodes',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_id'), 'episodes', ['id'], unique=False)
    op.create_index(op.f('ix_episodes_story_id'), 'episodes', ['story_id'], unique=False)
    op.create_table('address_matrixs',
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['speaker_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_matrixs_id'), 'address_matrixs', ['id'], unique=False)
    op.create_index(op.f('ix_address_matrixs_speaker_id'), 'address_matrixs', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_address_matrixs_target_id'), 'address_matrixs', ['target_id'], unique=False)
    op.create_table('pages',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('prose', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_episode_id'), 'pages', ['episode_id'], unique=False)
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_table('transcript_lines',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_speech_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_lines_id'), 'transcript_lines', ['id'], unique=False)
    op.create_index(op.f('ix_transcript_lines_page_id'), 'transcript_lines', ['page_id'], unique=False)
    op.create_index(op.f('ix_transcript_lines_speaker_id'), 'transcript_lines', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_transcript_lines_target_id'), 'transcript_lines', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_lines_target_id'), table_name='transcript_lines')
    op.drop_index(op.f('ix_transcript_lines_speaker_id'), table_name='transcript_lines')
    op.drop_index(op.f('ix_transcript_lines_page_id'), table_name='transcript_lines')
    op.drop_index(op.f('ix_transcript_lines_id'), table_name='transcript_lines')
    op.drop_table('transcript_lines')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_episode_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_address_matrixs_target_id'), table_name='address_matrixs')
    op.drop_index(op.f('ix_address_matrixs_speaker_id'), table_name='address_matrixs')
    op.drop_index(op.f('ix_address_matrixs_id'), table_name='address_matrixs')
    op.drop_table('address_matrixs')
    op.drop_index(op.f('ix_episodes_story_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_characters_story_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_stories_story_name'), table_name='stories')
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_table('stories')
    # ### end Alembic commands ###

